#
# Myles "Mellurboo" Wilson 2023
#

#
#          VARIABLES KEY
#
# %sender% Player name of who sent the command
# %recipient% Player name of who received the command
#

levelCost: 3

#%sender%
Recipient_TPAPrompt: "§e %sender% Has requested to teleport to you, use /tpa accept or /tpa deny"
Recipient_YouAccepted: "§eTeleport Request from %sender% Accepted"
Recipient_Canceled: "§c%sender% Canceled the teleport request"
#%recipient%
Recipient_YouDenied: "§cyou denied %recipient%'s teleport request"
#supports no variables
Recipient_SenderNotOnline: "§cthe player who sent this request is no longer online!"

# Supports %recipient%
Sender_TPAPrompt: "§eTeleport request sent to %recipient%"
Sender_RecipientAccepted: "§e%recipient% Has accepted your TP request"
Sender_RecipientDenied: "§c%recipient% Has denied your teleport request"
Sender_RequestCanceled: "§cYou Canceled the Teleport request to %recipient%"
Sender_ExistingRequest: "§cYou and %recipient% already have a pending request, please handle that one first."
# Supports %sender%
Sender_TPToSelf: "you cannot teleport to yourself"
# No variables supported
Sender_NoTPARequests: "§cYou have no pending requests!"
Sender_RecipientNotOnline: "§cthis player either doesnt exist or is not online."
Sender_SpecifyPlayer: "please specify the target player"

#%cost% is exclusive to this entry
Sender_LowExp: "§cYou do not have enough exp to complete this request, cost: %cost%"

#TPA Toggle
TPADisabled: "§cAll teleport requests have been paused by an Admin"
TPAStatus: "§cTPA set to %state% for all players" #(state) will either be true or false, exclusive to this string!

AdminClosedAllRequests: "§cAll teleport requests were closed by an Admin"
ConfigReloaded: "§eChumTPA config reloaded!"
BadCommandUsage: "§cUsage: /tpa <player>"